### PR TITLE
Fix ProviderOperationLatency issues

### LINKED ISSUE #499: providerOperationMetrics.ProviderOperationLatency in many functions are only called when the call is sucessful
I assume we would want to log metrics for failed operations as well?

### PR DESCRIPTION
**Pull request by msftcoderdjw**
Some of the target providers pass the arguments to ProviderOperationLatency wrongly. Needs to fix it.
Also fix #499

### CODE REVIEW

**Review by iwangjintian — APPROVED** [review]

File: api/pkg/apis/v1alpha1/providers/stage/create/create.go [hunk 1]
```diff
@@ -185,7 +192,7 @@ func (i *CreateStageProvider) Process(ctx context.Context, mgrContext contexts.M
 					create,
 					functionName,
 					metrics.ProcessOperation,
-					metrics.DeleteOperationType,
```
Comment (Haishi2016) [inline api/pkg/apis/v1alpha1/providers/stage/create/create.go:188]: So we don't distinguish delete or udpate anymore?

Comment (msftcoderdjw) [reply api/pkg/apis/v1alpha1/providers/stage/create/create.go:188]: For stage provider, we can distinguish operation type. But considering target provider, it may consists of multiple update + remove operations, I am thinking it is better we could calculate per function level.

**Review by Haishi2016 — APPROVED** [review]
