### PR TITLE
avoid crashes if stage provider is not found.

### LINKED ISSUE #192: If a campaign has an invalid stage provider type, it causes the api process to crash when activated

### PR DESCRIPTION
**Pull request by Haishi2016**
fixes #192

### CODE REVIEW

File: api/pkg/apis/v1alpha1/managers/stage/stage-manager.go [hunk 1]
```diff
@@ -251,6 +251,12 @@ func (s *StageManager) HandleDirectTriggerEvent(ctx context.Context, triggerData
 		status.IsActive = false
 		return status
 	}
+	if provider == nil {
+		status.Status = v1alpha2.InternalError
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/managers/stage/stage-manager.go:255]: InternalError or BadRequest?

**Review by RemindD — APPROVED** [review]
