### PR TITLE
checking if the activation still exist for waitcount = 0

### LINKED ISSUE #299: Wait stage provider should not have endless wait
If WaitCount is not set or set to 0, there would be endless loop calling API server to check if objects exist or not. And there is no way to stop the loop even if you delete campaign or activations. It only stops when API crashes.

This is not a good behavior. We should have a maximum WaitCount

### PR DESCRIPTION
**Pull request by lirenjie95**
Fix #299 
According to related logs (see below), we can ensure now `providers.stage.wait` will check if the activation still exists, and it will exit the wait when found the activation is deleted.
```txt
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/vendors.(*ActivationsVendor).onActivations:135","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"9f312d87905ca73c","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"info","msg":"V (Activations Vendor): onActivations, method: GET","scope":"coa.runtime","time":"2024-09-11T16:45:54.271611653Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/providers/states/k8s.(*K8sStateProvider).Get:485","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"df6460ba1f8c1bce","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"info","msg":"  P (K8s State): get state workflow in namespace default","scope":"coa.runtime","time":"2024-09-11T16:45:54.271837023Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/providers/stage/wait.(*WaitStageProvider).Process:319","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"75d7fd347166a24f","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"info","msg":"  P (Wait Processor): waiting for objects to be ready...","scope":"providers.stage.wait","time":"2024-09-11T16:45:54.275894277Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/coa/pkg/apis/v1alpha2/providers/states/redisstate.(*RedisStateProvider).List:204","diagnostics":{"correlationId":"","resourceId":"","traceContext":{"spanId":"76a13db50416e456","traceId":"412126d5f61d97f25bdafce0822030c3"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"debug","msg":"  P (Redis State): list states with keyPrefix Scheduled.workflow.symphony","scope":"coa.runtime","time":"2024-09-11T16:46:03.728815685Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/managers/staging.(*StagingManager).Poll:72","instance":"symphony-api-7c4fcb8f85-jgct4","level":"debug","msg":" M (Staging): Polling...","scope":"coa.runtime","time":"2024-09-11T16:46:03.728848719Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/coa/pkg/apis/v1alpha2/bindings/http.decodeJWTTokenForIssuer:239","instance":"symphony-api-7c4fcb8f85-jgct4","level":"debug","msg":"Issuer: https://kubernetes.default.svc.cluster.local","scope":"coa.runtime","time":"2024-09-11T16:46:04.282157144Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/coa/pkg/apis/v1alpha2/bindings/http.JWT.JWT-fm.JWT.JWT.func1:132","instance":"symphony-api-7c4fcb8f85-jgct4","level":"debug","msg":"JWT: Validating token with k8s.","scope":"coa.runtime","time":"2024-09-11T16:46:04.282278825Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/vendors.(*ActivationsVendor).onActivations:135","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"839bab2f32cb052b","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"info","msg":"V (Activations Vendor): onActivations, method: GET","scope":"coa.runtime","time":"2024-09-11T16:46:04.286752824Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/providers/states/k8s.(*K8sStateProvider).Get:485","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"7ae4d829c840d94c","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"info","msg":"  P (K8s State): get state workflow in namespace default","scope":"coa.runtime","time":"2024-09-11T16:46:04.286860377Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/providers/states/k8s.(*K8sStateProvider).Get:505","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"7ae4d829c840d94c","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"error","msg":"  P (K8s State) Not Found: failed to get object (caused by: activations.workflow.symphony \"workflow\" not found)","scope":"coa.runtime","time":"2024-09-11T16:46:04.289340709Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/vendors.(*ActivationsVendor).onActivations:159","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"7ae4d829c840d94c","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"info","msg":"V (Activations Vendor): onActivations failed - Not Found: failed to get object (caused by: activations.workflow.symphony \"workflow\" not found)","scope":"coa.runtime","time":"2024-09-11T16:46:04.289601376Z","type":"log","ver":"unknown"}
{"caller":"github.com/eclipse-symphony/symphony/api/pkg/apis/v1alpha1/providers/stage/wait.(*WaitStageProvider).Process:316","diagnostics":{"correlationId":"3bed5474-84c4-477c-942a-cfe5c2b3f12f","resourceId":"","traceContext":{"spanId":"fae6b79261d6ecea","traceId":"179ce5d69657cc4d0e6a5ef184e32c36"}},"instance":"symphony-api-7c4fcb8f85-jgct4","level":"info","msg":"  P (Wait Processor): detected activation got deleted, exiting endless wait.","scope":"providers.stage.wait","time":"2024-09-11T16:46:04.289928331Z","type":"log","ver":"unknown"}
```

### CODE REVIEW

File: api/pkg/apis/v1alpha1/providers/stage/wait/wait.go [hunk 1]
```diff
@@ -301,6 +301,20 @@ func (i *WaitStageProvider) Process(ctx context.Context, mgrContext contexts.Man
 			return outputs, false, nil
 		}
 		counter++
+		if i.Config.WaitCount == 0 && counter%10 == 0 {
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/providers/stage/wait/wait.go:304]: What if WaitCount is a very large integer? I think we can have this check regardless of WaitCount

File: api/pkg/apis/v1alpha1/providers/stage/wait/wait.go [hunk 2]
```diff
@@ -301,6 +301,20 @@ func (i *WaitStageProvider) Process(ctx context.Context, mgrContext contexts.Man
...
+			// Avoid to check the activation status too frequently
+			activationName, ok := inputs["__activation"].(string)
+			if !ok || activationName == "" {
+				log.InfoCtx(ctx, "  P (Wait Processor): __activation is not provided, exiting endless wait.")
+				return outputs, false, nil
+			}
+			_, err := i.ApiClient.GetActivation(ctx, activationName, namespace, i.Config.User, i.Config.Password)
+			if err != nil {
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/providers/stage/wait/wait.go:312]: You need to check if error type is NotFound or not. We should not break the loop for other transient errors.

File: api/pkg/apis/v1alpha1/utils/apiclient.go [hunk 3]
```diff
@@ -560,6 +561,27 @@ func (a *apiClient) PublishActivationEvent(ctx context.Context, event v1alpha2.A
 	return nil
 }
 
+func (a *apiClient) GetActivation(ctx context.Context, activation string, namespace string, user string, password string) (model.ActivationState, error) {
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/utils/apiclient.go:564]: Add the function in symphony-api.go as well for those that are not token validation.

File: api/pkg/apis/v1alpha1/utils/apiclient.go [hunk 4]
```diff
@@ -560,6 +561,27 @@ func (a *apiClient) PublishActivationEvent(ctx context.Context, event v1alpha2.A
...
+	ret := model.ActivationState{}
+	token, err := a.tokenProvider(ctx, a.baseUrl, a.client, user, password)
+
+	if err != nil {
+		return ret, err
+	}
+
+	response, err := a.callRestAPI(ctx, "activations/registry/"+url.QueryEscape(activation)+"?namespace="+url.QueryEscape(namespace), "GET", nil, token)
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/utils/apiclient.go:572]: Handle the case when namespace is empty string

File: api/pkg/apis/v1alpha1/providers/stage/wait/wait.go [hunk 5]
```diff
@@ -301,6 +301,20 @@ func (i *WaitStageProvider) Process(ctx context.Context, mgrContext contexts.Man
 			return outputs, false, nil
 		}
 		counter++
+		if i.Config.WaitCount == 0 && counter%10 == 0 {
+			// Avoid to check the activation status too frequently
+			activationName, ok := inputs["__activation"].(string)
+			if !ok || activationName == "" {
+				log.InfoCtx(ctx, "  P (Wait Processor): __activation is not provided, exiting endless wait.")
+				return outputs, false, nil
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/providers/stage/wait/wait.go:309]: Shall we return error in this case rather than success?

File: api/pkg/apis/v1alpha1/utils/apiclient.go (hunk 4 above)
Comment (lirenjie95) [reply api/pkg/apis/v1alpha1/utils/apiclient.go:572]: We can discuss with our team

File: api/pkg/apis/v1alpha1/providers/stage/wait/wait.go (hunk 1 above)
Comment (lirenjie95) [reply api/pkg/apis/v1alpha1/providers/stage/wait/wait.go:304]: Added in the new version. Now we check activation deletion not only for waitcount = 0

File: api/pkg/apis/v1alpha1/utils/apiclient.go (hunk 4 above)
Comment (lirenjie95) [reply api/pkg/apis/v1alpha1/utils/apiclient.go:572]: #466

File: api/pkg/apis/v1alpha1/providers/stage/wait/wait.go [hunk 6]
```diff
@@ -301,6 +301,23 @@ func (i *WaitStageProvider) Process(ctx context.Context, mgrContext contexts.Man
...
+				log.InfoCtx(ctx, "  P (Wait Processor): __activation is not provided, exiting endless wait.")
+				return nil, false, err
+			}
+			_, err := i.ApiClient.GetActivation(ctx, activationName, namespace, i.Config.User, i.Config.Password)
+			if err != nil && strings.Contains(err.Error(), v1alpha2.NotFound.String()) {
+				// Since we use ApiClient to get the activation, not found error will become v1alpha2.InternalError
+				// format: utils.SummarySpecError{Code:\"Symphony API: [500]\", Message:\"Not Found: ..."}
+				// We need to check if it contains v1alpha2.NotFound
+				log.InfoCtx(ctx, "  P (Wait Processor): detected activation got deleted, exiting endless wait.")
+				return nil, false, err
```
Comment (msftcoderdjw) [inline api/pkg/apis/v1alpha1/providers/stage/wait/wait.go:317]: Given activation is deleted in this case, if we return err to stage-manager, will this cause problem?

Comment (lirenjie95) [reply api/pkg/apis/v1alpha1/providers/stage/wait/wait.go:317]: In this case, the `providers.stage.wait` fails since we can't get all required objects. The stage manager will receive the error shows that `providers.stage.wait` quits since the activation does not exist any more. I refined the error type in the new version.

**Review by msftcoderdjw — APPROVED** [review]
