### PR TITLE
check every single catalog instead of getting the list

### LINKED ISSUE #418: Materialize stage provider doesn't return clear error message
e.g. when materializing instance from catalog, it will list all catalogs then match the input name. When input name is wrong (catalog not exists), there's no clear error.

Current error message: "failed to create all objects"

### PR DESCRIPTION
**Pull request by lirenjie95**
### MaterializeStageProvider Improvements:

* **Catalog Retrieval Logic**:
  - Changed from retrieving all catalogs at once to retrieving catalogs individually, which now uses a map to store catalog states.
  - Updated error handling to continue processing other catalogs if one fails, rather than terminating the entire process.

* **Object Creation Tracking**:
  - Replaced `creationCount` with a `createdObjectList` map to track successfully created objects more accurately.

* **Error Messaging**:
  - Enhanced error messages to specify which objects failed to be created.

### Test Case Updates:

* **Mock Symphony API**:
  - Updated mock responses to return individual catalog states instead of a list of catalogs, aligning with the new catalog retrieval logic.

Fix #418

### CODE REVIEW

File: api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go [hunk 1]
```diff
@@ -179,339 +179,355 @@ func (i *MaterializeStageProvider) Process(ctx context.Context, mgrContext conte
...
+		mLog.ErrorCtx(ctx, errorMessage)
 		providerOperationMetrics.ProviderOperationErrors(
 			materialize,
 			functionName,
 			metrics.ProcessOperation,
 			metrics.RunOperationType,
 			v1alpha2.CatalogsGetFailed.String(),
 		)
-		return outputs, false, err
+		return outputs, false, v1alpha2.NewCOAError(nil, errorMessage, v1alpha2.NotFound)
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go:204]: I am not sure if NotFound is appropriate for all errors. Sometimes getCatalog call can also failed with transient issue like service unavailability.

File: api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go [hunk 2]
```diff
@@ -179,339 +179,355 @@ func (i *MaterializeStageProvider) Process(ctx context.Context, mgrContext conte
...
-					}
 
-					// Check if labels exists within metadata, if not create it
-					labels, ok := metadata["labels"].(map[string]string)
-					if !ok {
-						labels = make(map[string]string)
-						metadata["labels"] = labels
-					}
+	createdObjectList := make(map[string]bool, 0)
+	for _, object := range prefixedNames {
```
Comment (RemindD) [inline api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go:208]: Is there any reason why you iterate over prefixedNames rather than catalogs map? And is it possible that exist==false in line 211?

Comment (lirenjie95) [reply api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go:208]: 1. The `prefixNames` can be used to log the names of catalogs easier. (line 525)
2. `exist == false` cannot happen since we have already checked `len(catalogs) < len(prefixedNames)` (line 195)

File: api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go (hunk 1 above)
Comment (lirenjie95) [reply api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go:204]: How about `v1alpha2.CatalogsGetFailed`?

File: api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go (hunk 2 above)
Comment (RemindD) [reply api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go:208]: catalogs names can also be retrieved from catalog object

File: api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go (hunk 1 above)
Comment (RemindD) [reply api/pkg/apis/v1alpha1/providers/stage/materialize/materialize.go:204]: I would prefer to return badrequest for NotFound errors so that we won't retry and return InternalError state for all others.

**Review by msftcoderdjw — APPROVED** [review]

**Review by msftcoderdjw — APPROVED** [review]

**Review by RemindD — APPROVED** [review]
