### PR TITLE
Fix middleware.http.telemetry config parser issue and add tests

### LINKED ISSUE #128: maxBatchSize and maxBatchInterval parsing in middleware.http.telemetry config
1. `middleware.http.telemetry` config only allows `float64` maxBatchSize/maxBatchInterval, `int` type should be added.
2. README and symphony-api jsons use `maxBatchIntervalSeconds`. https://github.com/search?q=repo%3Aeclipse-symphony%2Fsymphony+maxBatchIntervalSeconds&type=code `maxBatchInterval` should be renamed to `maxBatchIntervalSeconds`.

https://github.com/eclipse-symphony/symphony/blob/e0d08a86434c4247f985f702d6ba3959439f7340/coa/pkg/apis/v1alpha2/bindings/http/telemetry.go#L31-L40

### PR DESCRIPTION
**Pull request by msftcoderdjw**
**Changes**

- Fix #128 
- Add more tests

Files | Previous (%) | Now (%) | Notes
-- | -- | -- | --
./pkg/apis/v1alpha2/bindings/http/jwt.go | 0 | 90.3 |  
./pkg/apis/v1alpha2/bindings/http/trail.go | 0 | 100 |  
./pkg/apis/v1alpha2/bindings/http/telemetry.go | 0 | 82.4 | ENABLE_APP_INSIGHT and APP_INSIGHT_KEY configured
./pkg/apis/v1alpha2/bindings/http/cors.go | 0 | 100 |  
./pkg/apis/v1alpha2/bindings/http/http_pipeline.go | 0 | 97.4 |  
./pkg/apis/v1alpha2/bindings/http/tracing.go | 65.8 | 75 |  
./pkg/apis/v1alpha2/bindings/http/http.go | 0 | 87.5 |  
./pkg/apis/v1alpha2/bindings/mqtt/mqtt.go | 67.6 | 85.3 |

### CODE REVIEW

File: coa/pkg/apis/v1alpha2/bindings/http/telemetry.go [hunk 1]
```diff
@@ -28,15 +28,23 @@ func initClient(properties map[string]interface{}) {
 		instrumentationKey = "0be0a36e-6e0a-4544-a453-a237fd25cf64"
```
[the remark this answers is not in the document]
Comment (msftcoderdjw) [reply coa/pkg/apis/v1alpha2/bindings/http/telemetry.go]: Agree. Have removed default instrumentationKey.

File: coa/pkg/apis/v1alpha2/bindings/http/telemetry.go [hunk 2]
```diff
@@ -24,19 +24,24 @@ var initialized bool
 
 func initClient(properties map[string]interface{}) {
 	instrumentationKey := os.Getenv("APP_INSIGHT_KEY")
-	if instrumentationKey == "" {
-		instrumentationKey = "0be0a36e-6e0a-4544-a453-a237fd25cf64"
-	}
 	telemetryConfig := appinsights.NewTelemetryConfiguration(instrumentationKey)
```
Comment (Haishi2016) [inline coa/pkg/apis/v1alpha2/bindings/http/telemetry.go:27]: What happens if the key is missing?

Comment (msftcoderdjw) [reply coa/pkg/apis/v1alpha2/bindings/http/telemetry.go]: You are right, I have added a check in `http_pipeline.go` to validate the existence of env var - `APP_INSIGHT_KEY`. If it is missing, will return `BadConfig` error. Meanwhile, I also guard the existence of env var in initClient. If absence, will set `initialized = false`
